export const BALADYA_ARABIC: Record<string, string> = {
  "Abadla": "العبادلة",
  "Abelsa": "ابلسة",
  "Abi Youcef": "أبي يوسف",
  "Abou El Hassane": "أبو الحسن",
  "Achaacha": "عشعاشة",
  "Adekar": "أدكار",
  "Afir": "أعفير",
  "Aflou": "أفلو",
  "Aghbal": "أغبال",
  "Aghbalou": "أغبالو",
  "Aghlal": "أغلال",
  "Aghribs": "أغريب",
  "Agouni Gueghrane": "أقني قغران",
  "Ahl El Ksar": "أهل القصر",
  "Ahmed Rachedi": "أحمد راشدي",
  "Ahmer El Ain": "أحمر العين",
  "Ain Abessa": "عين عباسة",
  "Ain Abid": "عين عبيد",
  "Ain Amguel": "عين امقل",
  "Ain Arnat": "عين أرنات",
  "Ain Azel": "عين أزال",
  "Ain Babouche": "عين ببوش",
  "Ain Beida": "عين البيضاء",
  "Ain Beida Harriche": " عين البيضاء أحريش",
  "Ain Ben Beida": "عين بن بيضاء",
  "Ain Ben Khelil": "عين بن خليل",
  "Ain Benian": "عين بنيان",
  "Ain Biya": "عين البية",
  "Ain Bouchekif": "عين بوشقيف",
  "Ain Boucif": "عين بوسيف",
  "Ain Bouziane": "عين بوزيان",
  "Ain Charchar": "عين شرشار",
  "Ain Chouhada": "عين الشهداء",
  "Ain Deheb": "عين الذهب",
  "Ain Diss": "عين الديس",
  "Ain Djasser": "عين جاسر",
  "Ain Dzarit": "عين دزاريت",
  "Ain El Arbaa": "عين الأربعاء",
  "Ain El Assel": "عين العسل",
  "Ain El Berd": "عين البرد",
  "Ain El Berda": "عين الباردة",
  "Ain El Hadid": "عين الحديد",
  "Ain El Hadjar": "عين الحجر",
  "Ain El Hadjel": "عين الحجل",
  "Ain El Hammam": "عين الحمام",
  "Ain El Ibel": "عين الإبل",
  "Ain El Kebira": "عين الكبيرة",
  "Ain El Melh": "عين الملح",
  "Ain El Orak": "عين العراك",
  "Ain Fares": "عين فارس",
  "Ain Fekan": "عين فكان",
  "Ain Fekka": "عين فقه",
  "Ain Fekroun": "عين فكرون",
  "Ain Ferah": "عين فراح",
  "Ain Fetah": "عين فتاح",
  "Ain Fezza": "عين فزة",
  "Ain Frass": "عين أفرص",
  "Ain Ghoraba": "عين غرابة",
  "Ain Guezzam": "عين قزام",
  "Ain Kada": "عين قادة",
  "Ain Kebira": "عين الكبيرة",
  "Ain Kechra": "عين قشرة",
  "Ain Kercha": "عين كرشة",
  "Ain Kerma": "عين الكرمة",
  "Ain Kermes": "عين كرمس",
  "Ain Khadra": "عين الخضراء",
  "Ain Kihal": "عين الكيحل",
  "Ain Lahdjar": "عين الحجر",
  "Ain Laloui": "عين العلوي",
  "Ain Larbi": "عين العربي",
  "Ain M'lila": "عين مليلة",
  "Ain Maabed": "عين معبد",
  "Ain Madhi": "عين ماضي",
  "Ain Makhlouf": "عين مخلوف",
  "Ain Mellouk": "عين الملوك",
  "Ain Merane": "عين مران",
  "Ain Naga": "عين الناقة",
  "Ain Nehala": "عين النحالة",
  "Ain Ouksir": "عين اقصير",
  "Ain Oulmene": "عين ولمان",
  "Ain Oussera": "عين وسارة",
  "Ain Rahma": "عين الرحمة",
  "Ain Regada": "عين رقادة",
  "Ain Rich": "عين الريش",
  "Ain Romana": "عين الرمانة",
  "Ain Salah": "عين صالح",
  "Ain Sandel": "عين صندل",
  "Ain Sefra": "عين الصفراء",
  "Ain Sekhouna": "عين السخونة",
  "Ain Sidi Ali": "عين سيدي علي",
  "Ain Smara": "عين السمارة",
  "Ain Soltane": "عين السلطان",
  "Ain Taghrout": "عين تاغروت",
  "Ain Tagourait": "عين تاقورايت",
  "Ain Taya": "عين طاية",
  "Ain Tellout": "عين تالوت",
  "Ain Temouchent": "عين تموشنت",
  "Ain Tesra": "عين تسرة",
  "Ain Thrid": "عين الثريد",
  "Ain Tindamine": "عين تندمين",
  "Ain Tine": "عين التين",
  "Ain Tolba": "عين الطلبة",
  "Ain Touila": "عين الطويلة",
  "Ain Touta": "عين التوتة",
  "Ain Turk": "عين الترك",
  "Ain Yagout": "عين ياقوت",
  "Ain Youcef": "عين يوسف",
  "Ain Zaatout": "عين زعطوط",
  "Ain Zana": "عين الزانة",
  "Ain Zaouia": "عين الزاوية",
  "Ain Zerga": "عين الزرقاء",
  "Ain Zitoun": "عين الزيتون",
  "Ain Zouit": "عين زويت",
  "Ain- Adden": "عين أدن",
  "Ain-Benian": "عين البنيان",
  "Ain-Bessem": "عين بسام",
  "Ain-Boudinar": "عين بودينار",
  "Ain-Bouyahia": "عين بويحيى",
  "Ain-Defla": "عين الدفلى",
  "Ain-Lechiakh": "عين الاشياخ",
  "Ain-Legradj": "عين لقراج",
  "Ain-Nouissy": "عين نويسي",
  "Ain-Roua": "عين الروى",
  "Ain-Sebt": "عين السبت",
  "Ain-Sidi Cherif": "عين سيدي الشريف",
  "Ain-Soltane": "عين السلطان",
  "Ain-Tarek": "عين طارق",
  "Ain-Tedles": "عين تادلس",
  "Ain-Torki": "عين التركي",
  "Aissaouia": "العيساوية",
  "Ait Aggouacha": "أيت عقـواشة",
  "Ait Aissa Mimoun": "أيت عيسى ميمون",
  "Ait Bouaddou": "أيت بــوادو",
  "Ait Boumahdi": "أيت بومهدي",
  "Ait Chafaa": "أيت شافع",
  "Ait Khellili": "أيت خليلي",
  "Ait Laaziz": "أيت لعزيز",
  "Ait Mahmoud": "أيت محمود",
  "Ait Naoual Mezada": "أيت نوال مزادة",
  "Ait Oumalou": "أيت  أومالو",
  "Ait R'zine": "أيت رزين",
  "Ait Smail": "أيت إسماعيل",
  "Ait Toudert": "أيت تودرت",
  "Ait Yahia": "أيت يحيى",
  "Ait Yahia Moussa": "أيت يحي موسى",
  "Ait-Tizi": "ايت تيزي",
  "Akbil": "اقبيل",
  "Akbou": "أقبو",
  "Akerrou": "أقرو",
  "Akfadou": "أكفادو",
  "Alaimia": "العلايمية",
  "Alger Centre": "الجزائر الوسطى",
  "Amalou": "أمالو",
  "Amarnas": "العمارنة",
  "Amieur": "عمير",
  "Amira Arres": "اعميرة اراس",
  "Amizour": "أميزور",
  "Ammal": "عمال",
  "Ammari": "عماري",
  "Ammi Moussa": "عمي موسى",
  "Amoucha": "عموشة",
  "Amourah": "عمورة",
  "Annaba": "عنابة",
  "Aokas": "أوقاس",
  "Aomar": "أعمر",
  "Aoubellil": "عقب الليل",
  "Aouf": "عوف",
  "Aougrout": "أوقروت",
  "Arbaouat": "اربوات",
  "Arib": "عريب",
  "Arris": "أريس",
  "Arzew": "أرزيو",
  "Asfour": "عصفور",
  "Asla": "عسلة",
  "Assi Youcef": "أسي يوسف",
  "Ath Mansour": "آث  منصور",
  "Attatba": "الحطاطبة",
  "Azail": "العزايل",
  "Azazga": "عزازقة",
  "Azeffoun": "أزفون",
  "Azil Abedelkader": "عزيل عبد القادر",
  "Aziz": "عزيز",
  "Azzaba": "عزابة",
  "B. B. Arreridj": "برج بوعريرج",
  "Baata": "بعطة",
  "Bab El Assa": "باب العسة",
  "Bab El Oued": "باب الوادي",
  "Bab Ezzouar": "باب الزوار",
  "Baba Hassen": "بابا حسن",
  "Babar": "بابار",
  "Babor": "بابور",
  "Bachedjerah": "باش جراح",
  "Baghai": "بغاي",
  "Baghlia": "بغلية",
  "Baraki": "براقي",
  "Barbacha": "برباشة",
  "Barika": "بريكة",
  "Bathia": "بطحية",
  "Batna": "باتنة",
  "Bayadha": "البياضة",
  "Bazer-Sakra": "بازر سكرة",
  "Bechar": "بشار",
  "Bechloul": "بشلول",
  "Bedjene": "بجن",
  "Bedrabine El Mokrani": "بضرابين المقراني",
  "Behir Chergui": "بحير الشرقي",
  "Beidha Bordj": "بيضاء برج",
  "Bejaia": "بجاية",
  "Bekkaria": "بكارية",
  "Bekkouche Lakhdar": "بكوش لخضر",
  "Belaas": "بلعاص",
  "Belaassel Bouzagza": "بلعسل بوزقزة",
  "Belaiba": "بلعايبة",
  "Belarbi": "بلعربي",
  "Belimour": "بليمور",
  "Belkheir": "بلخير",
  "Bellaa": "بلاعة",
  "Ben Aknoun": "ابن عكنون",
  "Ben Allal": "بن علال",
  "Ben Azzouz": "بن عزوز",
  "Ben Badis": "بن باديس",
  "Ben Chicao": "بن شكاو",
  "Ben Choud": "بن شود",
  "Ben Daoud": "بن داود",
  "Ben Freha": "بن فريحة",
  "Ben Guecha": "بن  قشة",
  "Ben M Hidi": "بن مهيدي",
  "Ben Srour": "بن سرور",
  "Benabdelmalek Ramdane": "بن عبد المالك رمضان",
  "Benacer Benchohra": "بن ناصر بن شهرة",
  "Benaceur": "بن ناصر",
  "Benachiba Chelia": "بن عشيبة شلية",
  "Benairia": "بنايرية",
  "Bendaoud": "بن داود",
  "Bendjarah": "بن جراح",
  "Benhar": "بنهار",
  "Beni  Bouattab": "بني بوعتاب",
  "Beni Aissi": "بني عيسي",
  "Beni Amrane": "بني عمران",
  "Beni Bahdel": "بني بهدل",
  "Beni Bechir": "بني بشير",
  "Beni Boussaid": "بني بوسعيد",
  "Beni Chaib": "بني شعيب",
  "Beni Chebana": "بني شبانة",
  "Beni Dergoun": "بني درقن",
  "Beni Djellil": "بني جليل",
  "Beni Douala": "بني دوالة",
  "Beni Fouda": "بني فودة",
  "Beni Foudhala El Hakania": "بني فضالة الحقانية",
  "Beni Hamidane": "بني حميدان",
  "Beni Haoua": "بني حواء",
  "Beni Ilmane": "بني يلمان",
  "Beni K'sila": "بني كسيلة",
  "Beni Khellad": "بني خلاد",
  "Beni Lahcene": "بني لحسن",
  "Beni Mallikeche": "بني مليكش",
  "Beni Mered": "بني مراد",
  "Beni Messous": "بني مسوس",
  "Beni Mester": "بني مستر",
  "Beni Mezline": "بني مزلين",
  "Beni Mileuk": "بني ميلك",
  "Beni Ouarsous": "بني وارسوس",
  "Beni Oulbane": "بني ولبان",
  "Beni Ounif": "بني ونيف",
  "Beni Ourtilane": "بني ورتيلان",
  "Beni Oussine": "بني وسين",
  "Beni Rached": "بني راشد",
  "Beni Saf": "بني صاف",
  "Beni Slimane": "بني سليمان",
  "Beni Smiel": "بني صميل",
  "Beni Snous": "بني سنوس",
  "Beni Tamou": "بني تامو",
  "Beni Yenni": "بني يني",
  "Beni Zentis": "بني زنطيس",
  "Beni Zid": "بني زيد",
  "Beni Zikki": "بني زيكــي",
  "Beni Zmenzer": "بنــــي زمنزار",
  "Beni-Abbes": "بني عباس",
  "Beni-Aziz": "بني عزيز",
  "Beni-Ikhlef": "بن يخلف",
  "Beni-Mouhli": "بني موحلي",
  "Benian": "بنيان",
  "Benimaouche": "بني معوش",
  "Benkhelil": "بن خليل",
  "Bensekrane": "بن سكران",
  "Benyagoub": "بن يعقوب",
  "Benyahia Abderrahmane": "بن يحي عبد الرحمن",
  "Benzouh": "بن زوه",
  "Berhoum": "برهوم",
  "Berrahal": "برحال",
  "Berriane": "بريان",
  "Berriche": "بريش",
  "Berrihane": "بريحان",
  "Berrouaghia": "البرواقية",
  "Besbes": "البسباس",
  "Bethioua": "بطيوة",
  "Bin El Ouiden": "بين الويدان",
  "Bir Ben Laabed": "بئر بن عابد",
  "Bir Bouhouche": "بئر بوحوش",
  "Bir Chouhada": "بئر الشهداء",
  "Bir Dheheb": "بئر الذهب",
  "Bir El Djir": "بئر الجير",
  "Bir El Hammam": "بئر الحمام",
  "Bir Foda": "بئر فضة",
  "Bir Ghbalou": "بئر غبالو",
  "Bir Haddada": "بئر حدادة",
  "Bir Kasdali": "بئر قاصد علي",
  "Bir Mokkadem": "بئر مقدم",
  "Bir Mourad Rais": "بئر مراد رايس",
  "Bir Touta": "بئر توتة",
  "Bir-El-Arch": "بئر العرش",
  "Bir-El-Ater": "بئر العاتر",
  "Bir-Ould-Khelifa": "بئر ولد خليفة",
  "Birbouche": "بربوش",
  "Birine": "بيرين",
  "Birkhadem": "بئر خادم",
  "Biskra": "بسكرة",
  "Bitam": "بيطام",
  "Blida": "البليدة",
  "Blidet Amor": "بلدة اعمر",
  "Boghar": "بوغار",
  "Boghni": "بوغني",
  "Bologhine Ibnou Ziri": "بولوغين بن زيري",
  "Bordj Badji Mokhtar": "برج باجي مختار",
  "Bordj Ben Azzouz": "برج بن عزوز",
  "Bordj Bounaama": "برج بونعامة",
  "Bordj El Bahri": "برج البحري",
  "Bordj El Emir Abdelkader": "برج الأمير عبد القادر",
  "Bordj El Haouass": "برج الحواس",
  "Bordj El Kiffan": "برج الكيفان",
  "Bordj Ghedir": "برج الغدير",
  "Bordj Menaiel": "برج منايل",
  "Bordj Okhriss": "برج أوخريص",
  "Bordj Omar Driss": "برج عمر إدريس",
  "Bordj Sabath": "برج صباط",
  "Bordj T'har": "برج الطهر",
  "Bordj Zemmoura": "برج زمورة",
  "Bordj-Emir-Khaled": "برج الأمير خالد",
  "Bou Hachana": "بوحشانة",
  "Bou Hamdane": "بوحمدان",
  "Bou Haroun": "بوهارون",
  "Bou Henni": "بوهني",
  "Bou Ismail": "بواسماعيل",
  "Bou Saada": "بوسعادة",
  "Bouaiche": "بوعيش",
  "Bouaichoune": "بوعيشون",
  "Boualem": "بوعلام",
  "Bouandas": "بوعنداس",
  "Bouarfa": "بوعرفة",
  "Bouati Mahmoud": "بوعاتي محمود",
  "Boucaid": "بوقائد",
  "Bouchakroun": "بوشقرون",
  "Bouchegouf": "بوشقوف",
  "Bouchetata": "بوشطاطة",
  "Bouchrahil": "بوشراحيل",
  "Bouderbala": "بودربالة",
  "Boudjebaa El Bordj": "بوجبهة البرج",
  "Boudjellil": "بو جليل",
  "Boudjima": "بوجيمة",
  "Boudouaou": "بودواو",
  "Boudouaou El Bahri": "بودواو البحري",
  "Boudria Beniyadjis": "بودريعة بني  ياجيس",
  "Boufarik": "بوفاريك",
  "Boufatis": "بوفاتيس",
  "Bougaa": "بوقاعة",
  "Bougara": "بوقرة",
  "Boughzoul": "بوغزول",
  "Bougous": "بوقوس",
  "Bougtoub": "بوقطب",
  "Bouguirat": "بوقيراط",
  "Bouhadjar": "بوحجار",
  "Bouhamza": "بوحمزة",
  "Bouhanifia": "بوحنيفية",
  "Bouhatem": "بوحاتم",
  "Bouhlou": "بوحلو",
  "Bouhmama": "بوحمامة",
  "Bouihi": "البويهي",
  "Bouinan": "بوعينان",
  "Bouira": "البويرة",
  "Bouira Lahdab": "بويرة الأحداب",
  "Boukadir": "بوقادير",
  "Boukais": "بوكايس",
  "Boukhadra": "بوخضرة",
  "Boukhanefis": "بوخنفيس",
  "Boukhelifa": "بوخليفة",
  "Boukram": "بوكرم",
  "Boulhaf Dyr": "بولحاف الدير",
  "Boulhilat": "بولهيلات",
  "Boumagueur": "بومقر",
  "Boumahra Ahmed": "بومهرة أحمد",
  "Boumedfaa": "بومدفع",
  "Boumerdes": "بومرداس",
  "Boumia": "بومية",
  "Bounouh": "بونوح",
  "Bounoura": "بونورة",
  "Bourached": "بوراشد",
  "Bouraoui Belhadef": "بوراوي بلهادف",
  "Bourkika": "بورقيقة",
  "Bourouba": "بوروبة",
  "Bousfer": "بوسفر",
  "Bouskene": "بوسكن",
  "Bousselam": "بوسلام",
  "Boussemghoun": "بوسمغون",
  "Boussif Ouled Askeur": "بوسيف أولاد عسكر",
  "Boutaleb": "بوطالب",
  "Bouteldja": "بوثلجة",
  "Bouti Sayeh": "بوطي السايح",
  "Boutlelis": "بوتليليس",
  "Bouzareah": "بوزريعة",
  "Bouzedjar": "بوزجار",
  "Bouzeghaia": "بوزغاية",
  "Bouzeguene": "بوزقــن",
  "Bouzegza Keddara": "بوزقزة قدارة",
  "Bouzina": "بوزينة",
  "Branis": "برانيس",
  "Breira": "بريرة",
  "Brezina": "بريزينة",
  "Brida": "بريدة",
  "Casbah": "القصبة",
  "Chaabat El Ham": "شعبة اللحم",
  "Chabet El Ameur": "شعبة العامر",
  "Chabounia": "الشهبونية",
  "Chahna": "الشحنة",
  "Chaiba": "الشعيبة",
  "Charef": "الشارف",
  "Charouine": "شروين",
  "Chebaita Mokhtar": "شبيطة مختار",
  "Chebli": "الشبلي",
  "Chechar": "ششار",
  "Chefia": "الشافية",
  "Cheguig": "الشقيق",
  "Chehaima": "شحيمة",
  "Chekfa": "الشقفة",
  "Chelalet El Adhaoura": "شلالة العذاورة",
  "Chelghoum Laid": "شلغوم العيد",
  "Chelia": "شلية",
  "Chellal": "شلال",
  "Chellala": "شلالة",
  "Chellata": "شلاطة",
  "Chemini": "شميني",
  "Chemora": "الشمرة",
  "Cheniguel": "شنيقل",
  "Chentouf": "شنتوف",
  "Cheraga": "الشراقة",
  "Cheraia": "الشرايع",
  "Cherchell": "شرشال",
  "Cheria": "الشريعة",
  "Chetaibi": "شطايبي",
  "Chetma": "شتمة",
  "Chetouane": "شتوان",
  "Chetouane Belaila": "شيطوان البلايلة",
  "Chettia": "الشطية",
  "Cheurfa": "الشرفة",
  "Chiffa": "الشفة",
  "Chigara": "الشيقارة",
  "Chihani": "شحاني",
  "Chir": "شير",
  "Chlef": "الشلف",
  "Chorfa": "شرفة",
  "Chrea": "الشريعة",
  "Colla": "القلة",
  "Collo": "القل",
  "Constantine": "قسنطينة",
  "Corso": "قورصو",
  "Dahmouni": "دحموني",
  "Dahouara": "الدهوارة",
  "Dahra": "الظهرة",
  "Damous": "الداموس",
  "Dar Ben Abdelah": "دار بن عبد الله",
  "Dar Chioukh": "دار الشيوخ",
  "Dar El Beida": "الدار البيضاء",
  "Dar Yaghmoracen": "دار يغمراسن",
  "Darguina": "درقينة",
  "Debdeb": "دبداب",
  "Debila": "الدبيلة",
  "Dechmia": "الدشمية",
  "Dehahna": "دهاهنة",
  "Dehamcha": "الدهامشة",
  "Deldoul": "دلدول",
  "Dellys": "دلس",
  "Dely Ibrahim": "دالي ابراهيم",
  "Derrag": "دراق",
  "Derrahi Bousselah": "دراحي بوصلاح",
  "Dhalaa": "الضلعة",
  "Dhaya": "الضاية",
  "Dhayet Bendhahoua": "ضاية بن ضحوة",
  "Didouche Mourad": "ديدوش مراد",
  "Dirah": "ديرة",
  "Djaafra": "جعافرة",
  "Djamaa": "جامعة",
  "Djanet": "جانت",
  "Djasr Kasentina": "جسر قسنطينة",
  "Djebabra": "جبابرة",
  "Djebahia": "جباحية",
  "Djebala": "جبالة",
  "Djeballah Khemissi": "جبالة الخميسي",
  "Djebel Messaad": "جبل مساعد",
  "Djebilet Rosfa": "جبيلات الرصفاء",
  "Djelfa": "الجلفة",
  "Djelida": "جليدة",
  "Djellal": "جلال",
  "Djemaa Beni Habibi": "الجمعة بني حبيبي",
  "Djemaa Ouled Cheikh": "جمعة أولاد الشيخ",
  "Djemila": "جميلة",
  "Djemorah": "جمورة",
  "Djendel": "جندل",
  "Djendel Saadi Mohamed": "جندل سعدي محمد",
  "Djenienne Bourezg": "جنين بورزق",
  "Djerma": "جرمة",
  "Djezzar": "الجزار",
  "Djidiouia": "جديوية",
  "Djillali Ben Amar": "جيلالي بن عمار",
  "Djimla": "جيملة",
  "Djinet": "جنات",
  "Djouab": "جواب",
  "Douaouda": "دواودة",
  "Douar El Maa": "دوار الماء",
  "Doucen": "الدوسن",
  "Doui Thabet": "دوي ثابت",
  "Douira": "الدويرة",
  "Douis": "دويس",
  "Dra El Caid": "ذراع القايد",
  "Draa Ben Khedda": "ذراع بن خدة",
  "Draa El Mizan": "ذراع الميزان",
  "Draa Esmar": "ذراع السمار",
  "Draa-Kebila": "ذراع قبيلة",
  "Draria": "الدرارية",
  "Drea": "الدريعة",
  "Drean": "الذرعـان",
  "Echatt": "الشط",
  "El Achir": "الياشير",
  "El Achour": "العاشور",
  "El Adjiba": "العجيبة",
  "El Affroun": "العفرون",
  "El Aioun": "العيون",
  "El Alia": "العالية",
  "El Amiria": "العامرية",
  "El Amria": "العامرية",
  "El Ancer": "العنصر",
  "El Ancor": "العنصر",
  "El Annasseur": "العناصر",
  "El Aouana": "العوانة",
  "El Aricha": "العريشة",
  "El Arrouch": "الحروش",
  "El Asnam": "الأسنام",
  "El Assafia": "العسافية",
  "El Atteuf": "العطف",
  "El Ayadi Barbes": "العياضي برباس",
  "El Azizia": "العزيزية",
  "El Bayadh": "البيض",
  "El Beidha": "البيضاء",
  "El Belala": "البلالة",
  "El Biar": "الابيار",
  "El Biodh": "البيوض",
  "El Bnoud": "البنود",
  "El Bordj": "البرج",
  "El Borma": "البرمة",
  "El Bouni": "البوني",
  "El Braya": "البراية",
  "El Djazia": "الجازية",
  "El Euch": "العش",
  "El Eulma": "العلمة",
  "El Fedjoudj": "الفجوج",
  "El Fedjoudj Boughrara Sa": "الفجوج بوغرارة سعودي",
  "El Fehoul": "الفحول",
  "El Feidh": "الفيض",
  "El Gaada": "القعدة",
  "El Ghedir": "الغدير",
  "El Ghicha": "الغيشة",
  "El Ghomri": "الغمري",
  "El Ghrous": "الغروس",
  "El Gor": "القور",
  "El Guedid": "القديد",
  "El Gueitena": "القطنة",
  "El Guelbelkebir": "القلب الكبير",
  "El Guerrara": "القرارة",
  "El H'madna": "الحمادنة",
  "El Hacaiba": "الحصيبة",
  "El Hachem": "الحشم",
  "El Hachimia": "الهاشمية",
  "El Hadaiek": "الحدائق",
  "El Hadjab": "الحاجب",
  "El Hadjadj": "الحجاج",
  "El Hadjar": "الحجار",
  "El Hamdania": "الحمدانية",
  "El Hamel": "الهامل",
  "El Hamma": "الحامة",
  "El Haouaita": "الحويطة",
  "El Haouch": "الحوش",
  "El Haoudane": "الحوضان",
  "El Harmilia": "الحرملية",
  "El Harrach": "الحراش",
  "El Hassasna": "الحساسنة",
  "El Hassi": "الحاسي",
  "El Houamed": "الحوامد",
  "El Idrissia": "الادريسية",
  "El Kala": "القالة",
  "El Kantara": "القنطرة",
  "El Karimia": "الكريمية",
  "El Kennar Nouchfi": "القنار نشفي",
  "El Kerma": "الكرمة",
  "El Keurt": "القرط",
  "El Khabouzia": "الخبوزية",
  "El Kharrouba": "الخروبة",
  "El Kheiter": "الخيثر",
  "El Khemis": "الخميس",
  "El Khroub": "الخروب",
  "El Kouif": "الكويف",
  "El Kseur": "القصر",
  "El M'hir": "المهير",
  "El Madania": "المدنية",
  "El Madher": "المعذر",
  "El Magharia": "المغارية",
  "El Mahmal": "المحمل",
  "El Main": "الماين",
  "El Malabiod": "الماء الابيض",
  "El Maleh": "المالح",
  "El Mamounia": "المأمونية",
  "El Marsa": "المرسى",
  "El Mechira": "مشيرة",
  "El Mehara": "المحرة",
  "El Menaouer": "المنور",
  "El Meniaa": "المنيعة",
  "El Meridj": "المريج",
  "El Messaid": "المساعيد",
  "El Mezeraa": "المزرعة",
  "El Milia": "الميلية",
  "El Mouradia": "المرادية",
  "El Ogla": "العقلة",
  "El Ogla El Malha": "العقلة المالحة",
  "El Omaria": "العمارية",
  "El Ouata": "الواتة",
  "El Oueldja": "الولجة",
  "El Ouinet": "العوينات",
  "El Ouldja": "الولجة",
  "El Ouricia": "أوريسيا",
  "El Outaya": "الوطاية",
  "El Tarf": "الطارف",
  "El-Abadia": "العبادية",
  "El-Amra": "العامرة",
  "El-Aouinet": "العوينات",
  "El-Attaf": "العطاف",
  "El-Guettar": "القطار",
  "El-Hadjira": "الحجيرة",
  "El-Hakimia": "الحاكمية",
  "El-Houidjbet": "الحويجبات",
  "El-M'ghaier": "المغير",
  "El-Maine": "الماين",
  "El-Matmar": "المطمر",
  "El-Mokrani": "المقراني",
  "El-Oued": "الوادي",
  "El-Ouldja": "الولجة",
  "Elhammadia": "الحمادية",
  "Emir Abdelkader": "الامير عبد القادر",
  "Emjez Edchich": "مجاز الدشيش",
  "Ensigha": "انسيغة",
  "Erg Ferradj": "عرق فراج",
  "Erraguene Souissi": "أراقن سويسي",
  "Es Sebt": "السبت",
  "Es Senia": "السانية",
  "Faidh El Botma": "فيض البطمة",
  "Faidja": "الفايجة",
  "Fellaoucene": "فلاوسن",
  "Fenaia Il Maten": "فناية الماثن",
  "Feraoun": "فرعون",
  "Ferdjioua": "فرجيوة",
  "Ferkane": "فركان",
  "Ferraguig": "فراقيق",
  "Fesdis": "فسديس",
  "Filfila": "فلفلة",
  "Fkirina": "فكيرينة",
  "Foggaret Ezzoua": "فقارة الزوى",
  "Fornaka": "فرناقة",
  "Foughala": "فوغالة",
  "Fouka": "فوكة",
  "Foum Toub": "فم الطوب",
  "Freha": "فريحة",
  "Frenda": "فرندة",
  "Frikat": "فريقات",
  "Froha": "فروحة",
  "Gdyel": "قديل",
  "Ghailasa": "غيلاسة",
  "Ghardaia": "غرداية",
  "Gharrous": "غروس",
  "Ghassira": "غسيرة",
  "Ghassoul": "الغاسول",
  "Ghazaouet": "الغزوات",
  "Ghebala": "غبالة",
  "Ghriss": "غريس",
  "Gosbat": "القصبات",
  "Gouraya": "قوراية",
  "Grarem Gouga": "القرارم قوقة",
  "Guelaat Bou Sbaa": "قلعة بوصبع",
  "Guellal": "قلال",
  "Guelma": "قالمة",
  "Guelta Zerka": "قلتة زرقاء",
  "Gueltat Sidi Saad": "قلتة سيدي سعد",
  "Guemar": "قمار",
  "Guenzet": "قنزات",
  "Guerdjoum": "قرجوم",
  "Guernini": "قرنيني",
  "Guerrouaou": "قرواو",
  "Guerrouma": "قرومة",
  "Guertoufa": "قرطوفة",
  "Guettara": "قطارة",
  "Guidjel": "قجال",
  "Guigba": "القيقبة",
  "Guorriguer": "قريقر",
  "Hacine": "حسين",
  "Had Echkalla": "حد الشكالة",
  "Had Sahary": "حد الصحاري",
  "Haddada": "الحدادة",
  "Hadj Mechri": "الحاج مشري",
  "Hadjadj": "حجاج",
  "Hadjera Zerga": "الحجرة الزرقاء",
  "Hadjout": "حجوط",
  "Hadjret Ennous": "حجرة النص",
  "Haizer": "حيزر",
  "Hamadia": "حمادية",
  "Hamala": "حمالة",
  "Hamam Soukhna": "حمام السخنة",
  "Hamma": "الحامة",
  "Hamma Bouziane": "حامة بوزيان",
  "Hammadi Krouma": "حمادي كرومة",
  "Hammam Beni Salah": "حمام بني صالح",
  "Hammam Bou Hadjar": "حمام بوحجر",
  "Hammam Boughrara": "حمام بوغرارة",
  "Hammam Dalaa": "حمام الضلعة",
  "Hammam Debagh": "حمام دباغ",
  "Hammam Elouane": "حمام ملوان",
  "Hammam Guergour": "حمام قرقور",
  "Hammam N'bail": "حمام النبايل",
  "Hammam-Righa": "حمام ريغة",
  "Hammamet": "الحمامات",
  "Hammedi": "حمادي",
  "Hamraia": "الحمراية",
  "Hamri": "حمري",
  "Hanchir Toumghani": "هنشير تومغني",
  "Hanencha": "الحنانشة",
  "Hanif": "حنيف",
  "Hannacha": "حناشة",
  "Haraza": "حرازة",
  "Harbil": "حربيل",
  "Harchoun": "حرشون",
  "Hasnaoua": "حسناوة",
  "Hassani Abdelkrim": "حساني عبد الكريم",
  "Hassania": "الحسانية",
  "Hassasna": "الحساسنة",
  "Hassi Bahbah": "حاسي بحبح",
  "Hassi Ben Abdellah": "حاسي بن عبد الله",
  "Hassi Ben Okba": "حاسي بن عقبة",
  "Hassi Bounif": "حاسي بونيف",
  "Hassi Dahou": "حاسي دحو",
  "Hassi Delaa": "حاسي الدلاعة",
  "Hassi El Euch": "حاسي العش",
  "Hassi El Ghella": "حاسي الغلة",
  "Hassi Fedoul": "حاسي فدول",
  "Hassi Fehal": "حاسي الفحل",
  "Hassi Gara": "حاسي القارة",
  "Hassi Khalifa": "حاسي خليفة",
  "Hassi Mameche": "حاسي ماماش",
  "Hassi Mefsoukh": "حاسي مفسوخ",
  "Hassi Messaoud": "حاسي مسعود",
  "Hassi R'mel": "حاسي الرمل",
  "Hassi Zahana": "حاسي زهانة",
  "Hassiane": "الحسيان (بني ياحي",
  "Heliopolis": "هيليوبوليس",
  "Hennaya": "الحناية",
  "Herenfa": "الهرانفة",
  "Herraoua": "هراوة",
  "Hidoussa": "حيدوسة",
  "Hoceinia": "الحسينية",
  "Honnaine": "هنين",
  "Houari Boumedienne": "هواري بومدين",
  "Hounet": "هونت",
  "Hussein Dey": "حسين داي",
  "Hydra": "حيدرة",
  "Ibn Ziad": "ابن زياد",
  "Iboudrarene": "إبودرارن",
  "Ichemoul": "إشمول",
  "Idjeur": "إيجــار",
  "Idles": "أدلس",
  "Iferhounene": "إفــرحــونان",
  "Ifigha": "إيفيغاء",
  "Iflissen": "إفليـــسن",
  "Ighil Ali": "إغيل علي",
  "Ighram": "اغرم",
  "Igli": "إقلي",
  "Illilten": "إيلـيــلتـن",
  "Illizi": "إيليزي",
  "Illoula Oumalou": "إيلولة أومـــالو",
  "Imsouhal": "إمســوحال",
  "In Amenas": "إن أمناس",
  "Inghar": "إينغر",
  "Inoughissen": "إينوغيسن",
  "Irdjen": "إيرجـــن",
  "Isser": "يسر",
  "Jijel": "جيجل",
  "Kadiria": "قادرية",
  "Kais": "قايس",
  "Kalaa": "القلعة",
  "Kanoua": "قنواع",
  "Kaous": "قاوس",
  "Kasdir": "القصدير",
  "Kasr El Abtal": "قصر الابطال",
  "Kef El Ahmar": "الكاف الأحمر",
  "Kef Lakhdar": "الكاف الاخضر",
  "Kenadsa": "القنادسة",
  "Kendira": "كنديرة",
  "Kerkara": "الكركرة",
  "Kerzaz": "كرزاز",
  "Khadra": "خضرة",
  "Khalouia": "خلوية",
  "Khams Djouamaa": "خمس جوامع",
  "Khedara": "الخضارة",
  "Kheir-Eddine": "خير الدين",
  "Khelil": "خليل",
  "Khemis El Khechna": "خميس الخشنة",
  "Khemis-Miliana": "خميس مليانة",
  "Khemissa": "خميسة",
  "Khemisti": "خميستي",
  "Khenag Maoune": "خناق مايو",
  "Khenchela": "خنشلة",
  "Kheneg": "الخنق",
  "Khenguet Sidi Nadji": "خنقة سيدي ناجي",
  "Kherrata": "خراطة",
  "Khettouti Sed-El-Jir": "خطوطي سد الجير",
  "Khezaras": "لخزارة",
  "Khirane": "خيران",
  "Khiri Oued Adjoul": "خيري واد عجول",
  "Khoubana": "خبانة",
  "Khraissia": "الخرايسية",
  "Kimmel": "كيمل",
  "Kolea": "القليعة",
  "Kouba": "القبة",
  "Kouinine": "كوينين",
  "Krakda": "كراكدة",
  "Ksabi": "القصابي",
  "Ksar Bellezma": "قصر بلزمة",
  "Ksar Chellala": "قصر الشلالة",
  "Ksar El Boukhari": "قصر البخاري",
  "Ksar El Hirane": "قصر الحيران",
  "Ksar Kaddour": "قصر قدور",
  "Ksar Sbahi": "قصر الصباحي",
  "Ksour": "القصور",
  "Labiod Medjadja": "الأبيض مجاجة",
  "Labiodh Sidi Cheikh": "الأبيض سيدي الشيخ",
  "Lac Des Oiseaux": "بحيرة الطيور",
  "Laghouat": "الأغواط",
  "Lahlef": "لحلاف",
  "Lahmar": "لحمر",
  "Lakhdaria": "الأخضرية",
  "Lamtar": "لمطار",
  "Larbaa": "لارباع",
  "Larbaa Nath Irathen": "الأربعــاء ناث إيراثن",
  "Larbatache": "الاربعطاش",
  "Lardjem": "لرجام",
  "Larhat": "الأرهاط",
  "Layoune": "العيون",
  "Lazharia": "الأزهرية",
  "Lazrou": "لازرو",
  "Leflaye": "الفلاي",
  "Leghata": "لقاطة",
  "Lemcene": "لمسان",
  "Les Eucalyptus": "الكاليتوس",
  "Lichana": "ليشانة",
  "Lioua": "ليوة",
  "M Chedallah": "أمشدالة",
  "M Doukal": "إمدوكل",
  "M'chouneche": "مشونش",
  "M'cid": "مسيد",
  "M'cif": "مسيف",
  "M'cisna": "مسيسنة",
  "M'daourouche": "مداوروش",
  "M'fatha": "مفاتحة",
  "M'kira": "مكيرة",
  "M'lili": "مليلي",
  "M'liliha": "مليليحة",
  "M'naguer": "المنقر",
  "M'rara": "المرارة",
  "M'sara": "مصارة",
  "M'sila": "المسيلة",
  "M'sirda Fouaga": "مسيردة الفواقة",
  "M'tarfa": "المطارفة",
  "M'toussa": "متوسة",
  "Maacem": "المعاصم",
  "Maadid": "المعاضيد",
  "Maafa": "معافة",
  "Maala": "معلة",
  "Maalma": "المعالمة",
  "Maamora": "المعمورة",
  "Maaouia": "معاوية",
  "Maarif": "معاريف",
  "Maatkas": "معـــاتقة",
  "Machraa Houari Boumediene": "مشرع هواري بومدين",
  "Machroha": "المشروحة",
  "Madna": "مادنة",
  "Maghnia": "مغنية",
  "Maghraoua": "مغراوة",
  "Magra": "مقرة",
  "Magrane": "المقرن",
  "Mahdia": "مهدية",
  "Makedra": "مكدرة",
  "Makhda": "ماقضة",
  "Makmen Ben Amar": "مكمن بن عمار",
  "Makouda": "ماكودة",
  "Mansoura": "المنصورة",
  "Mansourah": "منصورة",
  "Maouaklane": "ماوكلان",
  "Maoussa": "ماوسة",
  "Marhoum": "مرحوم",
  "Marsa Ben M'hidi": "مرسى بن مهيدي",
  "Marsat El Hadjadj": "مرسى الحجاج",
  "Mascara": "معسكر",
  "Matemore": "المطمور",
  "Mazagran": "مزغران",
  "Mazouna": "مازونة",
  "Mecheria": "المشرية",
  "Mechraa Safa": "مشرع الصفا",
  "Mechtras": "مشطراس",
  "Medea": "المدية",
  "Mediouna": "مديونة",
  "Medjana": "مجانة",
  "Medjebar": "مجبر",
  "Medjedel": "امجدل",
  "Medjez Amar": "مجاز عمار",
  "Medjez Sfa": "مجاز الصفاء",
  "Medrissa": "مدريسة",
  "Medroussa": "مدروسة",
  "Meftah": "مفتاح",
  "Megarine": "المقارين",
  "Meghila": "مغيلة",
  "Mekhadma": "مخادمة",
  "Mekhatria": "المخاطرية",
  "Mekla": "مقــلع",
  "Melaab": "الملعب",
  "Melbou": "مالبو",
  "Mellakou": "ملاكو",
  "Menaa": "منعة",
  "Menaceur": "مناصر",
  "Mendes": "منداس",
  "Merad": "مراد",
  "Merahna": "المراهنة",
  "Merdja Sidi Abed": "مرجة سيدي عابد",
  "Meridja": "المريجة",
  "Merine": "مرين",
  "Merouana": "مروانة",
  "Mers El Kebir": "المرسى الكبير",
  "Meskiana": "مسكيانة",
  "Mesra": "ماسرة",
  "Messaad": "مسعد",
  "Messaoud Boudjeriou": "بوجريو مسعود",
  "Messelmoun": "مسلمون",
  "Messerghin": "مسرغين",
  "Metarfa": "المطارفة",
  "Metlili": "متليلي",
  "Mezaourou": "مزاورو",
  "Mezdour": "مزدور",
  "Mezerana": "مزغنة",
  "Meziraa": "المزيرعة",
  "Mezloug": "مزلوق",
  "Mih Ouansa": "اميه وانسة",
  "Mihoub": "ميهوب",
  "Mila": "ميلة",
  "Miliana": "مليانة",
  "Minar Zarza": "مينار زارزة",
  "Mizrana": "ميزرانـــة",
  "Mocta-Douz": "مقطع الدوز",
  "Mogheul": "موغل",
  "Moghrar": "مغرار",
  "Mohamed Belouzdad": "محمد بلوزداد",
  "Mohamed Boudiaf": "محمد بوضياف",
  "Mohammadia": "المحمدية",
  "Morsott": "مرسط",
  "Mostaganem": "مستغانم",
  "Mostefa  Ben Brahim": "مصطفى بن ابراهيم",
  "Moudjebara": "مجبارة",
  "Moulay Larbi": "مولاي العربي",
  "Moulay Slissen": "مولاي سليسن",
  "Moussadek": "مصدق",
  "Mouzaia": "موزاية",
  "N Gaous": "نقاوس",
  "N'goussa": "انقوسة",
  "Naama": "النعامة",
  "Naciria": "الناصرية",
  "Nador": "الناظور",
  "Nadorah": "الناظورة",
  "Naima": "النعيمة",
  "Nakhla": "النخلة",
  "Nechmaya": "نشماية",
  "Nedroma": "ندرومة",
  "Negrine": "نقرين",
  "Nekmaria": "نكمارية",
  "Nesmot": "نسمط",
  "Nezla": "النزلة",
  "Oggaz": "عقاز",
  "Oran": "وهران",
  "Ouacif": "واسيف",
  "Ouadhias": "واضية",
  "Ouaguenoun": "واقنون",
  "Ouamri": "عوامري",
  "Ouanougha": "ونوغة",
  "Ouargla": "ورقلة",
  "Ouarizane": "واريزان",
  "Oudjana": "وجانة",
  "Oued Athmenia": "وادي العثمانية",
  "Oued Berkeche": "وادي برقش",
  "Oued Chaaba": "وادي الشعبة",
  "Oued Cheham": "وادي الشحم",
  "Oued Chorfa": "وادي الشرفاء",
  "Oued Djemaa": "واد الجمعة",
  "Oued Djer": "وادي جر",
  "Oued El Abtal": "وادي الأبطال",
  "Oued El Alenda": "وادي العلندة",
  "Oued El Alleug": "وادي العلايق",
  "Oued El Aneb": "واد العنب",
  "Oued El Bared": "واد البارد",
  "Oued El Berdi": "وادي البردي",
  "Oued El Djemaa": "وادي الجمعة",
  "Oued El Kheir": "وادي الخير",
  "Oued El Ma": "وادي الماء",
  "Oued Endja": "وادي النجاء",
  "Oued Essalem": "وادي السلام",
  "Oued Ferragha": "وادي فراغة",
  "Oued Fodda": "وادي الفضة",
  "Oued Ghir": "وادي غير",
  "Oued Goussine": "وادي قوسين",
  "Oued Harbil": "وادي حربيل",
  "Oued Kebrit": "وادي الكبريت",
  "Oued Koriche": "وادي قريش",
  "Oued Lakhdar": "وادي الخضر",
  "Oued Lilli": "وادي ليلي",
  "Oued M'zi": "وادي مزي",
  "Oued Morra": "وادي مرة",
  "Oued Nini": "وادي نيني",
  "Oued Sebaa": "وادي السبع",
  "Oued Sebbah": "وادي الصباح",
  "Oued Sefioun": "وادي سفيون",
  "Oued Seguen": "وادي سقان",
  "Oued Sly": "وادي سلي",
  "Oued Smar": "وادي السمار",
  "Oued Taga": "وادي الطاقة",
  "Oued Taourira": "وادي تاوريرة",
  "Oued Taria": "وادي التاغية",
  "Oued Tlelat": "وادي تليلات",
  "Oued Zenati": "وادي الزناتي",
  "Oued Zhour": "وادي الزهور",
  "Oued Zitoun": "وادي الزيتون",
  "Oued-Rhiou": "وادي رهيو",
  "Ouenza": "الونزة",
  "Ouillen": "ويلان",
  "Ouldja Boulbalout": "الولجة بولبلوط",
  "Ouled Abbes": "أولاد عباس",
  "Ouled Addi Guebala": "أولاد عدي لقبالة",
  "Ouled Addouane": "أولاد عدوان",
  "Ouled Aiche": "أولاد يعيش",
  "Ouled Aissa": "أولاد عيسى",
  "Ouled Ammar": "أولاد عمار",
  "Ouled Antar": "أولاد عنتر",
  "Ouled Aouf": "أولاد عوف",
  "Ouled Attia": "أولاد عطية",
  "Ouled Ben Abdelkader": "أولاد بن عبد القادر",
  "Ouled Bessam": "أولاد بسام",
  "Ouled Bouachra": "أولاد بوعشرة",
  "Ouled Boudjemaa": "أولاد بوجمعة",
  "Ouled Boughalem": "أولاد بوغالم",
  "Ouled Brahem": "أولاد أبراهم",
  "Ouled Brahim": "أولاد إبراهيم",
  "Ouled Chebel": "اولاد شبل",
  "Ouled Dahmane": "أولاد دحمان",
  "Ouled Deid": "أولاد دايد",
  "Ouled Derradj": "أولاد دراج",
  "Ouled Djellal": "أولاد جلال",
  "Ouled Driss": "أولاد إدريس",
  "Ouled Emaaraf": "أولاد امعرف",
  "Ouled Fadel": "أولاد فاضل",
  "Ouled Fares": "أولاد فارس",
  "Ouled Fayet": "اولاد فايت",
  "Ouled Gacem": "أولاد قاسم",
  "Ouled Habbaba": "أولاد حبابة",
  "Ouled Hamla": "أولاد حملة",
  "Ouled Hedadj": "أولاد هداج",
  "Ouled Hellal": "أولاد هلال",
  "Ouled Khaled": "أولاد خالد",
  "Ouled Khalouf": "أولاد اخلوف",
  "Ouled Kihal": "أولاد الكيحل",
  "Ouled Madhi": "أولاد ماضي",
  "Ouled Mansour": "أولاد منصور",
  "Ouled Mimoun": "أولاد ميمون",
  "Ouled Moumen": "أولاد مومن",
  "Ouled Moussa": "أولاد موسى",
  "Ouled Rabah": "أولاد رابح",
  "Ouled Rached": "أولاد راشد",
  "Ouled Rahmoun": "أولاد رحمون",
  "Ouled Rechache": "أولاد رشاش",
  "Ouled Riyah": "أولاد رياح",
  "Ouled Sabor": "أولاد صابر",
  "Ouled Said": "أولاد السعيد",
  "Ouled Sellem": "أولاد سلام",
  "Ouled Si Ahmed": "أولاد سي أحمد",
  "Ouled Si Slimane": "أولاد سي سليمان",
  "Ouled Sidi Brahim": "أولاد سيدي ابراهيم",
  "Ouled Sidi Mihoub": "أولاد سيدي الميهوب",
  "Ouled Sidi-Brahim": "أولاد سيدي ابراهيم",
  "Ouled Slama": "اولاد سلامة",
  "Ouled Slimane": "أولاد سليمان",
  "Ouled Tebben": "أولاد تبان",
  "Ouled Yahia Khadrouch": "أولاد يحيى خدروش",
  "Ouled Yaich": "أولاد يعيش",
  "Ouled Zouai": "أولاد زواي",
  "Ouled-Khodeir": "أولاد خضير",
  "Ouled-Maalah": "أولاد مع الله",
  "Oulhaca El Gheraba": "ولهاصة الغرابة",
  "Oulteme": "ولتام",
  "Oum Ali": "أم علي",
  "Oum Drou": "أم الدروع",
  "Oum El Adhaim": "أم العظايم",
  "Oum El Assel": "أم العسل",
  "Oum El Bouaghi": "أم البواقي",
  "Oum El Djellil": "أم الجليل",
  "Oum Laadham": "أم العظام",
  "Oum Toub": "أم الطوب",
  "Oum Touyour": "أم الطيور",
  "Oumache": "أوماش",
  "Ourlal": "أورلال",
  "Ourmes": "ورماس",
  "Ouyoun El Assafir": "عيون العصافير",
  "Ouzellaguen": "أوزلاقن",
  "Ouzera": "وزرة",
  "Rabta": "الرابطة",
  "Ragouba": "الراقوبة",
  "Rahbat": "الرحبات",
  "Rahia": "الرحية",
  "Rahmania": "الرحمانية",
  "Rahouia": "الرحوية",
  "Rais Hamidou": "الرايس حميدو",
  "Ramdane Djamel": "رمضان جمال",
  "Ramka": "الرمكة",
  "Raml Souk": "رمل السوق",
  "Raouraoua": "روراوة",
  "Ras El Agba": "رأس العقبة",
  "Ras El Ain Amirouche": "رأس عين عميروش",
  "Ras El Aioun": "رأس العيون",
  "Ras El Ma": "راس الماء",
  "Ras El Miad": "رأس الميعاد",
  "Ras El Oued": "رأس الوادي",
  "Rebaia": "الربعية",
  "Rechaiga": "الرشايقة",
  "Redjem Demouche": "رجم دموش",
  "Reghaia": "رغاية",
  "Reguiba": "الرقيبة",
  "Relizane": "غليزان",
  "Remchi": "الرمشي",
  "Remila": "الرميلة",
  "Ridane": "ريدان",
  "Robbah": "الرباح",
  "Rogassa": "رقاصة",
  "Roknia": "الركنية",
  "Rosfa": "الرصفة",
  "Rouached": "الرواشد",
  "Rouiba": "الرويبة",
  "Rouina": "الروينة",
  "Rouissat": "الرويسات",
  "Sabra": "صبرة",
  "Saf Saf El Ouesra": "صفصاف الوسرى",
  "Safel El Ouiden": "سافل الويدان",
  "Safsaf": "صفصاف",
  "Saharidj": "سحاريج",
  "Saida": "سعيدة",
  "Salah Bey": "صالح باي",
  "Salah Bouchaour": "صالح بو الشعور",
  "Saneg": "السانق",
  "Sayada": "صيادة",
  "Sebaine": "السبعين",
  "Sebbaa Chioukh": "سبعة شيوخ",
  "Sebdou": "سبدو",
  "Sebgag": "سبقاق",
  "Sebseb": "سبسب",
  "Sebt": "السبت",
  "Sed Rahal": "سد الرحال",
  "Seddouk": "صدوق",
  "Sedjerara": "سجرارة",
  "Sedrata": "سدراتة",
  "Sedraya": "سدراية",
  "Sefiane": "سفيان",
  "Seggana": "سقانة",
  "Seghouane": "سغوان",
  "Sehailia": "السهايلية",
  "Sehala Thaoura": "السهالة الثورة",
  "Sehaoula": "السحاولة",
  "Sellaoua Announa": "سلاوة عنونة",
  "Selma Benziada": "سلمى بن زيادة",
  "Selmana": "سلمانة",
  "Sendjas": "سنجاس",
  "Seraidi": "سرايدي",
  "Serdj-El-Ghoul": "سرج الغول",
  "Serghine": "سرغين",
  "Seriana": "سريانة",
  "Setif": "سطيف",
  "Settara": "السطارة",
  "Sfisef": "سفيزف",
  "Sfissifa": "سفيسيفة",
  "Si Abdelghani": "سي عبد الغني",
  "Si Mahdjoub": "سي المحجوب",
  "Si Mustapha": "سي مصطفى",
  "Sidi Abdelaziz": "سيدي عبد العزيز",
  "Sidi Abdeldjebar": "سيدي عبد الجبار",
  "Sidi Abdelli": "سيدي العبدلي",
  "Sidi Abdelmoumene": "سيدي عبد المومن",
  "Sidi Abderrahmane": "سيدي عبد الرحمن",
  "Sidi Abed": "سيدي عابد",
  "Sidi Ahmed": "سيدي احمد",
  "Sidi Aissa": "سيدي عيسى",
  "Sidi Akkacha": "سيدي عكاشة",
  "Sidi Ali": "سيدي علي",
  "Sidi Ali Benyoub": "سيدي علي بن يوب",
  "Sidi Ali Boussidi": "سيدي علي بوسيدي",
  "Sidi Ali Mellal": "سيدي علي ملال",
  "Sidi Amar": "سيدي عمر",
  "Sidi Ameur": "سيدي عامر",
  "Sidi Amrane": "سيدي عمران",
  "Sidi Aoun": "سيدي عون",
  "Sidi Ayad": "سيدي عياد",
  "Sidi Baizid": "سيدي بايزيد",
  "Sidi Bakhti": "سيدي بختي",
  "Sidi Bel-Abbes": "سيدي بلعباس",
  "Sidi Belaattar": "سيدي بلعطار",
  "Sidi Ben Adda": "سيدي بن عدة",
  "Sidi Ben Yebka": "سيدي بن يبقى",
  "Sidi Boubekeur": "سيدي بوبكر",
  "Sidi Boumediene": "سيدي بومدين",
  "Sidi Boussaid": "سيدي بوسعيد",
  "Sidi Boutouchent": "سيدي بوتوشنت",
  "Sidi Bouzid": "سيدي بوزيد",
  "Sidi Brahim": "سيدي ابراهيم",
  "Sidi Chaib": "سيدي شعيب",
  "Sidi Chami": "سيدي الشحمي",
  "Sidi Dahou Zairs": "سيدي دحو الزاير",
  "Sidi Daoud": "سيدي داود",
  "Sidi Demed": "سيدي دامد",
  "Sidi Djillali": "سيدي الجيلالي",
  "Sidi Fredj": "سيدي فرج",
  "Sidi Ghiles": "سيدي غيلاس",
  "Sidi Hadjeres": "سيدي هجرس",
  "Sidi Hamadouche": "سيدي حمادوش",
  "Sidi Hosni": "سيدي حسني",
  "Sidi Kada": "سيدي قادة",
  "Sidi Khaled": "سيدي خالد",
  "Sidi Khelifa": "سيدي خليفة",
  "Sidi Khelil": "سيدي خليل",
  "Sidi Khettab": "سيدي  خطاب",
  "Sidi Khouiled": "سيدي خويلد",
  "Sidi Laadjel": "سيدي لعجال",
  "Sidi Lahcene": "سيدي لحسن",
  "Sidi Lantri": "سيدي العنتري",
  "Sidi Lazreg": "سيدي لزرق",
  "Sidi M'hamed": "سيدي امحمد",
  "Sidi M'hamed Benali": "سيدي أمحمد بن علي",
  "Sidi M'hamed Benaouda": "سيدي امحمد بن عودة",
  "Sidi Makhlouf": "سيدي مخلوف",
  "Sidi Marouf": "سيدي معروف",
  "Sidi Medjahed": "سيدي مجاهد",
  "Sidi Merouane": "سيدي مروان",
  "Sidi Mezghiche": "سيدي مزغيش",
  "Sidi Moussa": "سيدي موسى",
  "Sidi Naamane": "سيدي نعمان",
  "Sidi Namane": "سيدي نعمان",
  "Sidi Okba": "سيدي عقبة",
  "Sidi Ouriache": "سيدي ورياش",
  "Sidi Rabie": "سيدي الربيع",
  "Sidi Rached": "سيدي راشد",
  "Sidi Saada": "سيدي سعادة",
  "Sidi Safi": "سيدي صافي",
  "Sidi Semiane": "سيدي سميان",
  "Sidi Slimane": "سيدي سليمان",
  "Sidi Tiffour": "سيدي طيفور",
  "Sidi Yacoub": "سيدي يعقوب",
  "Sidi Zahar": "سيدي زهار",
  "Sidi Ziane": "سيدي زيان",
  "Sidi-Aich": "سيدي عيش",
  "Sidi-Amar": "سيدي عامر",
  "Sidi-Embarek": "سيدي أمبارك",
  "Sidi-Lakhdar": "سيدي لخضر",
  "Sig": "سيق",
  "Sigus": "سيقوس",
  "Sirat": "سيرات",
  "Skikda": "سكيكدة",
  "Slim": "سليم",
  "Smaoun": "سمعون",
  "Sobha": "الصبحة",
  "Souaflia": "السوافلية",
  "Souagui": "السواقي",
  "Souahlia": "السواحلية",
  "Souama": "صوامـــع",
  "Souamaa": "السوامع",
  "Souani": "السواني",
  "Souarekh": "السوارخ",
  "Sougueur": "السوقر",
  "Souhane": "صوحان",
  "Souidania": "سويدانية",
  "Souk Ahras": "سوق أهراس",
  "Souk El Had": "سوق الحد",
  "Souk El Khemis": "سوق الخميس",
  "Souk El Tenine": "سوق لإثنين",
  "Souk Naamane": "سوق نعمان",
  "Souk Oufella": "سوق اوفلا",
  "Souk Tleta": "سوق الثلاثاء",
  "Soumaa": "الصومعة",
  "Sour": "سور",
  "Sour El Ghozlane": "سور الغزلان",
  "Stah Guentis": "سطح قنطيس",
  "Staoueli": "سطاوالي",
  "Stidia": "ستيدية",
  "Still": "سطيل",
  "Stitten": "ستيتن",
  "T Kout": "تكوت",
  "Taadmit": "تعظميت",
  "Tabelbala": "تبلبالة",
  "Tabia": "طابية",
  "Tablat": "تابلاط",
  "Tacheta Zegagha": "تاشتة زقاغة",
  "Tachouda": "تاشودة",
  "Tadjemout": "تاجموت",
  "Tadjena": "تاجنة",
  "Tadjenanet": "تاجنانت",
  "Tadjrouna": "تاجرونة",
  "Tadmait": "تادمايت",
  "Tafraoui": "طفراوي",
  "Tafraout": "تفراوت",
  "Tagdempt": "تاقدمت",
  "Taghit": "تاغيت",
  "Taghzout": "تاغزوت",
  "Taglait": "تقلعيت",
  "Taguedite": "تاقديت",
  "Taher": "الطاهير",
  "Taibet": "الطيبات",
  "Takhemaret": "تخمرت",
  "Tala Hamza": "تالة حمزة",
  "Tala-Ifacene": "تالة إيفاسن",
  "Talassa": "تلعصة",
  "Taleb Larbi": "الطالب العربي",
  "Talkhamt": "تالخمت",
  "Talmine": "طالمين",
  "Tamalous": "تمالوس",
  "Tamanrasset": "تمنراست",
  "Tamellahet": "تملاحت",
  "Tamesguida": "تمسقيدة",
  "Tamlouka": "تاملوكة",
  "Tamokra": "تامقرة",
  "Tamridjet": "تامريجت",
  "Tamsa": "تامسة",
  "Tamtert": "تامترت",
  "Tamza": "طامزة",
  "Tamzoura": "تامزورة",
  "Taoudmout": "تاودموت",
  "Taougrit": "تاوقريت",
  "Taouiala": "تاويالة",
  "Taoura": "تاورة",
  "Taourga": "تاورقة",
  "Taourit Ighil": "تاوريرت إغيل",
  "Taouzianat": "تاوزيانت",
  "Tarik-Ibn-Ziad": "طارق بن زياد",
  "Tarmount": "تارمونت",
  "Taskriout": "تاسكريوت",
  "Tassadane Haddada": "تسدان حدادة",
  "Tassala Lematai": "تسالة لمطاعي",
  "Tassamert": "تسامرت",
  "Taxlent": "تاكسلانت",
  "Taya": "الطاية",
  "Tazgait": "تزقايت",
  "Tazmalt": "تازمالت",
  "Tazoult": "تازولت",
  "Tazrouk": "تاظروك",
  "Tebesbest": "تبسبست",
  "Tebessa": "تبسة",
  "Tefessour": "تفسور",
  "Tefreg": "تفرق",
  "Teghalimet": "تغاليمت",
  "Telagh": "تلاغ",
  "Teleghma": "التلاغمة",
  "Telidjen": "ثليجان",
  "Tella": "التلة",
  "Temacine": "تماسين",
  "Tenedla": "تندلة",
  "Tenes": "تنس",
  "Teniet El Abed": "ثنية العابد",
  "Teniet En Nasr": "ثنية النصر",
  "Tenira": "تنيرة",
  "Terga": "تارقة",
  "Terny Beni Hediel": "تيرني بني هديل",
  "Terraguelt": "ترقالت",
  "Terrai Bainen": "ترعي باينان",
  "Tessala": "تسالة",
  "Tessala El Merdja": "تسالة المرجة",
  "Texenna": "تاكسنة",
  "Thenia": "الثنية",
  "Theniet El Had": "ثنية الاحد",
  "Tianet": "تيانت",
  "Tiaret": "تيارت",
  "Tibane": "طيبان",
  "Tiberguent": "تيبرقنت",
  "Tiberkanine": "تبركانين",
  "Tichy": "تيشي",
  "Tidda": "تيدة",
  "Tidjelabine": "تيجلابين",
  "Tiffech": "تيفاش",
  "Tifra": "تيفرة",
  "Tighanimine": "تيغانمين",
  "Tigharghar": "تغرغار",
  "Tighennif": "تيغنيف",
  "Tigzirt": "تيقـزيرت",
  "Tilatou": "تيلاطو",
  "Tilmouni": "تلموني",
  "Timezrit": "تيمزريت",
  "Timgad": "تيمقاد",
  "Timiaouine": "تيمياوين",
  "Timimoun": "تيميمون",
  "Timizart": "تيمـيزار",
  "Timoudi": "تيمودي",
  "Tin Zouatine": "تين زواتين",
  "Tindouf": "تندوف",
  "Tinebdar": "تينبدار",
  "Tinerkouk": "تنركوك",
  "Tiout": "تيوت",
  "Tipaza": "تيبازة",
  "Tircine": "تيرسين",
  "Tirmitine": "تيرمتين",
  "Tissemsilt": "تيسمسيلت",
  "Tixter": "تيكستار",
  "Tizi": "تيزي",
  "Tizi Gheniff": "تيزي غنيف",
  "Tizi Mahdi": "تيزي مهدي",
  "Tizi N'bechar": "تيزي نبشار",
  "Tizi N'berber": "تيزي نبربر",
  "Tizi N'tleta": "تيزي نثلاثة",
  "Tizi Ouzou": "تيزي وزو",
  "Tizi Rached": "تيزي راشد",
  "Tlemcen": "تلمسان",
  "Tletat Ed Douair": "ثلاث دوائر",
  "Tolga": "طولقة",
  "Touahria": "الطواهرية",
  "Toudja": "توجة",
  "Touggourt": "تقرت",
  "Tousmouline": "توسمولين",
  "Tousnina": "توسنينة",
  "Treat": "التريعات",
  "Trifaoui": "الطريفاوي",
  "Yabous": "يابوس",
  "Yahia Beniguecha": "يحي بني قشة",
  "Yakourene": "إعــكورن",
  "Yatafene": "يطــافن",
  "Yellel": "يلل",
  "Youb": "يوب",
  "Youssoufia": "اليوسفية",
  "Z'barbar (El Isseri )": "زبربر",
  "Zaafrane": "زعفران",
  "Zaarouria": "الزعرورية",
  "Zaccar": "زكار",
  "Zahana": "زهانة",
  "Zanet El Beida": "زانة البيضاء",
  "Zaouia El Abidia": "الزاوية العابدية",
  "Zarzour": "زرزور",
  "Zeboudja": "الزبوجة",
  "Zeddine": "زدين",
  "Zeghaia": "زغاية",
  "Zekri": "زكري",
  "Zelamta": "زلامطة",
  "Zelfana": "زلفانة",
  "Zemmoura": "زمورة",
  "Zemmouri": "زموري",
  "Zenata": "زناتة",
  "Zeralda": "زرالدة",
  "Zerdezas": "زردازة",
  "Zeribet El Oued": "زريبة الوادي",
  "Zerizer": "زريزر",
  "Zerouala": "زروالة",
  "Ziama Mansouriah": "زيامة منصورية",
  "Zighoud Youcef": "زيغود يوسف",
  "Zitouna": "الزيتونة",
  "Zmalet El Emir Abdelkade": "زمالة  الأمير عبد القادر",
  "Zorg": "الزرق",
  "Zouabi": "الزوابي",
  "Zoubiria": "الزبيرية",
};
