export const ORDER_STATUS_MAP: Record<string, { label: string; labelAr: string; color: string; bgColor: string }> = {
  NEW:               { label: "New",               labelAr: "طلب جديد",                    color: "text-sky-600",      bgColor: "bg-sky-50" },
  CONFIRMED:         { label: "Confirmed",         labelAr: "تم التأكيد",                  color: "text-emerald-600",  bgColor: "bg-emerald-50" },
  NOT_ANSWERED_1:    { label: "Not Answered 1",    labelAr: "العميل لايرد",                color: "text-orange-600",   bgColor: "bg-orange-50" },
  NOT_ANSWERED_2:    { label: "Not Answered 2",    labelAr: "العميل لايرد 2",              color: "text-orange-600",   bgColor: "bg-orange-50" },
  NOT_ANSWERED_3:    { label: "Not Answered 3",    labelAr: "العميل لايرد 3",              color: "text-orange-600",   bgColor: "bg-orange-50" },
  PHONE_CLOSED_1:    { label: "Phone Closed 1",    labelAr: "الهاتف مغلق",                 color: "text-red-600",      bgColor: "bg-red-50" },
  PHONE_CLOSED_2:    { label: "Phone Closed 2",    labelAr: "الهاتف مغلق 2",               color: "text-red-600",      bgColor: "bg-red-50" },
  PHONE_CLOSED_3:    { label: "Phone Closed 3",    labelAr: "الهاتف مغلق 3",               color: "text-red-600",      bgColor: "bg-red-50" },
  OUT_OF_COVERAGE_1: { label: "Out of Coverage 1", labelAr: "خارج مجال التغطية",           color: "text-violet-600",   bgColor: "bg-violet-50" },
  OUT_OF_COVERAGE_2: { label: "Out of Coverage 2", labelAr: "خارج مجال التغطية 2",         color: "text-violet-600",   bgColor: "bg-violet-50" },
  OUT_OF_COVERAGE_3: { label: "Out of Coverage 3", labelAr: "خارج مجال التغطية 3",         color: "text-violet-600",   bgColor: "bg-violet-50" },
  CANCELLED:         { label: "Cancelled",         labelAr: "تم إلغاء الطلب",              color: "text-red-600",      bgColor: "bg-red-50" },
  FAKE:              { label: "Fake",              labelAr: "طلب وهمي",                    color: "text-gray-600",     bgColor: "bg-gray-50" },
  POSTPONED:         { label: "Postponed",         labelAr: "تم تأجيل الطلب",              color: "text-amber-600",    bgColor: "bg-amber-50" },
  WAITING_CALLBACK:  { label: "Waiting Callback",  labelAr: "في انتظار عودة اتصال العميل", color: "text-cyan-600",     bgColor: "bg-cyan-50" },
  SHIPPED:           { label: "Shipped",           labelAr: "تم الشحن",                    color: "text-blue-600",     bgColor: "bg-blue-50" },
  IN_DELIVERY:       { label: "In Delivery",       labelAr: "قيد التسليم",                 color: "text-blue-700",     bgColor: "bg-blue-50" },
  ON_HOLD:           { label: "On Hold",           labelAr: "معلق",                        color: "text-yellow-600",   bgColor: "bg-yellow-50" },
  DELIVERED:         { label: "Delivered",         labelAr: "تم التسليم",                  color: "text-emerald-600",  bgColor: "bg-emerald-50" },
  READY_FOR_PAYMENT: { label: "Ready for Payment", labelAr: "جاهز للدفع",                 color: "text-orange-600",   bgColor: "bg-orange-50" },
  PAID:              { label: "Paid",              labelAr: "مدفوع مكتمل",                 color: "text-green-600",    bgColor: "bg-green-50" },
  CUSTOMER_REORDERED:{ label: "Customer Reordered", labelAr: "العميل أعاد الطلب",          color: "text-teal-600",     bgColor: "bg-teal-50" },
  RETURN_TRANSFER:   { label: "Return Transfer",   labelAr: "مرجع قيد التحويل",            color: "text-red-600",      bgColor: "bg-red-50" },
  RETURN_READY:      { label: "Return Ready",      labelAr: "مرجع جاهز للاستلام",          color: "text-red-600",      bgColor: "bg-red-50" },
  RETURN_COMPLETED:  { label: "Return Completed",  labelAr: "مرجع مكتمل",                  color: "text-red-600",      bgColor: "bg-red-50" },
};

export const ORDER_STATUSES = Object.keys(ORDER_STATUS_MAP);

export const ATTEMPT_STATUSES = ["NOT_ANSWERED_1", "NOT_ANSWERED_2", "NOT_ANSWERED_3", "PHONE_CLOSED_1", "PHONE_CLOSED_2", "PHONE_CLOSED_3", "OUT_OF_COVERAGE_1", "OUT_OF_COVERAGE_2", "OUT_OF_COVERAGE_3"];
export const MAX_ATTEMPTS = 3;

export const WILAYAS_DATA = [
  { code: "01", name: "Adrar" },
  { code: "02", name: "Chlef" },
  { code: "03", name: "Laghouat" },
  { code: "04", name: "Oum El Bouaghi" },
  { code: "05", name: "Batna" },
  { code: "06", name: "Béjaïa" },
  { code: "07", name: "Biskra" },
  { code: "08", name: "Béchar" },
  { code: "09", name: "Blida" },
  { code: "10", name: "Bouira" },
  { code: "11", name: "Tamanrasset" },
  { code: "12", name: "Tébessa" },
  { code: "13", name: "Tlemcen" },
  { code: "14", name: "Tiaret" },
  { code: "15", name: "Tizi Ouzou" },
  { code: "16", name: "Alger" },
  { code: "17", name: "Djelfa" },
  { code: "18", name: "Jijel" },
  { code: "19", name: "Sétif" },
  { code: "20", name: "Saïda" },
  { code: "21", name: "Skikda" },
  { code: "22", name: "Sidi Bel Abbès" },
  { code: "23", name: "Annaba" },
  { code: "24", name: "Guelma" },
  { code: "25", name: "Constantine" },
  { code: "26", name: "Médéa" },
  { code: "27", name: "Mostaganem" },
  { code: "28", name: "M'Sila" },
  { code: "29", name: "Mascara" },
  { code: "30", name: "Ouargla" },
  { code: "31", name: "Oran" },
  { code: "32", name: "El Bayadh" },
  { code: "33", name: "Illizi" },
  { code: "34", name: "Bordj Bou Arreridj" },
  { code: "35", name: "Boumerdès" },
  { code: "36", name: "El Tarf" },
  { code: "37", name: "Tindouf" },
  { code: "38", name: "Tissemsilt" },
  { code: "39", name: "El Oued" },
  { code: "40", name: "Khenchela" },
  { code: "41", name: "Souk Ahras" },
  { code: "42", name: "Tipaza" },
  { code: "43", name: "Mila" },
  { code: "44", name: "Aïn Defla" },
  { code: "45", name: "Naâma" },
  { code: "46", name: "Aïn Témouchent" },
  { code: "47", name: "Ghardaïa" },
  { code: "48", name: "Relizane" },
  { code: "49", name: "Timimoun" },
  { code: "50", name: "Bordj Badji Mokhtar" },
  { code: "51", name: "Ouled Djellal" },
  { code: "52", name: "Beni Abbes" },
  { code: "53", name: "In Salah" },
  { code: "54", name: "In Guezzam" },
  { code: "55", name: "Touggourt" },
  { code: "56", name: "Djanet" },
  { code: "57", name: "El M'Ghair" },
  { code: "58", name: "El Meniaa" },
];

export const SHIPPING_PRICES: Record<string, { home: number; office: number }> = {
  "01": { home: 1000, office: 500 },
  "02": { home: 650, office: 400 },
  "03": { home: 800, office: 450 },
  "04": { home: 750, office: 400 },
  "05": { home: 750, office: 400 },
  "06": { home: 650, office: 400 },
  "07": { home: 800, office: 450 },
  "08": { home: 1000, office: 600 },
  "09": { home: 450, office: 200 },
  "10": { home: 600, office: 400 },
  "11": { home: 1200, office: 700 },
  "12": { home: 750, office: 500 },
  "13": { home: 750, office: 400 },
  "14": { home: 650, office: 400 },
  "15": { home: 600, office: 400 },
  "16": { home: 400, office: 200 },
  "17": { home: 800, office: 450 },
  "18": { home: 650, office: 400 },
  "19": { home: 600, office: 400 },
  "20": { home: 700, office: 400 },
  "21": { home: 650, office: 400 },
  "22": { home: 700, office: 400 },
  "23": { home: 650, office: 400 },
  "24": { home: 700, office: 400 },
  "25": { home: 650, office: 400 },
  "26": { home: 600, office: 400 },
  "27": { home: 650, office: 400 },
  "28": { home: 700, office: 400 },
  "29": { home: 650, office: 400 },
  "30": { home: 900, office: 500 },
  "31": { home: 650, office: 400 },
  "32": { home: 800, office: 500 },
  "33": { home: 1300, office: 550 },
  "34": { home: 650, office: 400 },
  "35": { home: 600, office: 400 },
  "36": { home: 700, office: 400 },
  "37": { home: 1200, office: 550 },
  "38": { home: 700, office: 400 },
  "39": { home: 800, office: 450 },
  "40": { home: 750, office: 450 },
  "41": { home: 750, office: 450 },
  "42": { home: 600, office: 400 },
  "43": { home: 650, office: 400 },
  "44": { home: 600, office: 400 },
  "45": { home: 800, office: 450 },
  "46": { home: 650, office: 350 },
  "47": { home: 850, office: 450 },
  "48": { home: 650, office: 350 },
  "49": { home: 1000, office: 550 },
  "51": { home: 900, office: 500 },
  "52": { home: 1100, office: 0 },
  "53": { home: 1100, office: 550 },
  "55": { home: 900, office: 450 },
  "57": { home: 900, office: 0 },
  "58": { home: 1000, office: 450 },
};

export const UNAVAILABLE_WILAYAS = ["50", "54", "56"];

// Delivery company status → Internal status mapping (from DHD CSV)
export const DELIVERY_STATUS_MAP: Record<string, string> = {
  prete_a_expedier: "SHIPPED",
  vers_wilaya: "IN_DELIVERY",
  en_preparation: "IN_DELIVERY",
  en_livraison: "IN_DELIVERY",
  suspendu: "ON_HOLD",
  livre_non_encaisse: "DELIVERED",
  encaisse_non_paye: "READY_FOR_PAYMENT",
  paye_et_archive: "PAID",
  retour_chez_livreur: "CUSTOMER_REORDERED",
  retour_en_traitement: "RETURN_TRANSFER",
  retour_recu: "RETURN_READY",
  retour_archive: "RETURN_COMPLETED",
};

export const OFFICES_DATA: Record<string, string[]> = {
  "01": ["Adrar"],
  "02": ["Chlef", "Tenes"],
  "03": ["Laghouat"],
  "04": ["Oum El Bouaghi", "Ain Fekroune"],
  "05": ["Batna", "Barika"],
  "06": ["Bejaia", "Kherrata"],
  "07": ["Biskra"],
  "08": ["Bechar"],
  "09": ["Blida", "Ouled Yaich", "Beni Mered", "Bouarfaik", "Bouinan"],
  "10": ["Bouira"],
  "11": ["Tamanrasset"],
  "12": ["Tebessa"],
  "13": ["Tlemcen", "Sebdou"],
  "14": ["Tiaret", "Ksar Chellala"],
  "15": ["Tizi Ouzou"],
  "16": ["Bab El Oued", "Bab Ezzouar", "Bir Touta", "Les Eucalyptus", "Cheraga", "Djasr Kasentina", "Kouba", "Draria", "Reghaia"],
  "17": ["Djelfa", "Ain Oussera"],
  "18": ["Jijel"],
  "19": ["Setif", "El Eulma"],
  "20": ["Saida"],
  "21": ["Skikda", "El Arrouch"],
  "22": ["Sidi Bel Abbes"],
  "23": ["Annaba", "El Bouni"],
  "24": ["Guelma"],
  "25": ["Constantine", "El Khroub"],
  "26": ["Medea"],
  "27": ["Mostaganem", "Mazagran"],
  "28": ["M'sila", "Bou Saada"],
  "29": ["Mascara", "Sig"],
  "30": ["Ouargla"],
  "31": ["Oran", "Bir El Djir", "Sidi Chami"],
  "32": ["El Bayadh"],
  "33": ["Illizi"],
  "34": ["Bordj Bou Arreridj"],
  "35": ["Boumerdes", "Bordj Menaiel"],
  "36": ["El Tarf"],
  "37": ["Tindouf"],
  "38": ["Tissemsilt"],
  "39": ["El Oued"],
  "40": ["Khenchela"],
  "41": ["Souk Ahras"],
  "42": ["Tipaza", "Kolea"],
  "43": ["Mila"],
  "44": ["Ain Defla", "Khemis Miliana"],
  "45": ["Mecheria"],
  "46": ["Ain Temouchent"],
  "47": ["Ghardaia"],
  "48": ["Relizane"],
  "49": ["Timimoun"],
  "51": ["Ouled Djellal"],
  "53": ["In Salah"],
  "55": ["Touggourt"],
  "58": ["El Meniaa"],
};
